---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest 
    pre_build_image: true
    command: /sbin/init
    systemd: yes
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  yamllint .

scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy

  converge_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
