---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Check url
      uri:
        url: "http://127.0.0.1:8080"
        status_code: 200
        return_content: yes
      register: content
    
    - name: Check content
      assert:
        that:
          - content.content == "Hello this is not a test"
          - content.status == 200
