---
- name: Ensure apache2 is installed
  apt:
    name: apache2
    state: present
    update_cache: true

- name: Change apache 2 default port
  replace:
    regexp: "^Listen 80$"
    replace: "Listen 8080"
    path: /etc/apache2/ports.conf


- name: Start httpd
  service:
    name: apache2
    state: started
    enabled: true

- name: Deploy content
  copy:
    content: "Hello this is a test"
    dest: /var/www/html/index.html
    mode: 0644
    owner: www-data
    group: www-data
