---
  name: my-CI
  'on':
    push:
      branches:
        - main
  
  defaults:
    run:
      working-directory: 'Ansible-Molecule-CI/webserver'


  jobs:
    molecule:
      name: Molecule
      runs-on: centos-latest
      strategy:
        matrix:
          include:
            - distro: ubuntu1804
            - distro: centos8

      steps:
        - name: checkout the codebase
          uses: actions/checkout@v2
          with:
            path: 'Ansible-Molecule-CI'

        - name: Set up python3
          uses: actions/setup-python@v2
          with:
            python-version: '3.x'
        
        - name: Install molecule dependencies
          run: pip3 install ansible molecule[podman] podman

        - name: Run molecule test
          run: molecule test
          env:
            PY_COLORS: '1'
            ANSIBLE_FORCE_COLOR: '1'
            MOLECULE_DISTRO: ${{ matrix.distro }}
